{% set name = "cfn-lint" %}
{% set version = "0.24.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b39911be25f31b72594c86ec3274e70a31bda84baf593b856f39f0a408a3a95d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfn-lint = cfnlint.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - six >=1.11,<2
    - aws-sam-translator >=1.13.0
    - jsonpatch
    - jsonschema >=3,<4
    - setuptools
    - pathlib2 >=2.3.0  # [py2k]

test:
  imports:
    - cfnlint
  commands:
    - cfn-lint -h

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT No Attribution
  license_family: MIT
  license_file: LICENSE
  summary: 'CloudFormation Linter'
  description: |
    Validate CloudFormation yaml/json templates against the 
    CloudFormation spec and additional checks. Includes checking 
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy
