{% set name = "cfn-lint" %}
{% set version = "0.87.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 749b7e52a2d83f1236e87ef9c244910ffff609bcdf357eab0814ed80c076de11

build:
  number: 0
  noarch: python
  entry_points:
    - cfn-lint = cfnlint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - pyyaml >5.4
    - aws-sam-translator >=1.87.0
    - jsonpatch
    - jsonschema >=3.0,<5
    - networkx >=2.4,<4
    - junit-xml >=1.9,<2.dev0
    - jschema-to-python >=1.2.3,<1.3.dev0
    - sarif-om >=1.0.4,<1.1.dev0
    - sympy >=1.0.0
    - regex >=2021.7.1

test:
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - pip check
    - cfn-lint --help
  requires:
    - pip

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
  license: MIT
  license_file: LICENSE
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint


extra:
  recipe-maintainers:
    - mariusvniekerk
    - hajapy
    - jan-janssen
