{% set name = "cfn-lint" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c79fd8487dda4451ffddaf98e239728ea345615d86a01da9e1067e5952ef1052

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfn-lint = cfnlint.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - six ~=1.11
    - requests >=2.15.0
    - aws-sam-translator >=1.10.0
    - jsonpatch
    - jsonschema ~=2.6
    - setuptools

test:
  imports:
    - cfnlint
  commands:
    - cfn-lint -h

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT No Attribution
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'CloudFormation Linter'
  description: |
    Validate CloudFormation yaml/json templates against the 
    CloudFormation spec and additional checks. Includes checking 
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy
