{% set name = "cfn-lint" %}
{% set version = "0.63.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cfn-lint-{{ version }}.tar.gz
  sha256: 7168df5dfbab51a5dce0c25530507edecdf359c99dcc3fc0871cd5de7cd81695

build:
  number: 0
  noarch: python
  entry_points:
    - cfn-lint = cfnlint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aws-sam-translator >=1.40.0
    - importlib_resources >=1.4,<4
    - jschema-to-python ~=1.2.3
    - jsonpatch
    - jsonschema ~=3.0
    - junit-xml ~=1.9
    - networkx ~=2.4
    - pyyaml >5.4
    - sarif-om ~=1.0.4
    - six >=1.11

test:
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - pip check
    - cfn-lint --help
  requires:
    - pip

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
  license: MIT
  license_file: LICENSE
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint


extra:
  recipe-maintainers:
    - mariusvniekerk
    - hajapy
