{% set name = "cfn-lint" %}
{% set version = "1.32.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 10282c0ec7fc6391da4877d9381a6b954f3c54ddcc0d3c97ee86f4783b5ae680

build:
  number: 0
  noarch: python
  entry_points:
    - cfn-lint = cfnlint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.5.1
  run:
    - typing_extensions
    - python >={{ python_min }},<4.0
    - pyyaml >5.4
    - aws-sam-translator >=1.95.0
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.0.0
    - regex
    - typing-extensions
    - pydot
    - junit-xml >=1.9,<2.dev0
    - jschema-to-python >=1.2.3,<1.3.dev0
    - sarif-om >=1.0.4,<1.1.dev0

test:
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
  license: MIT
  license_file: LICENSE
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint


extra:
  recipe-maintainers:
    - mariusvniekerk
    - hajapy
    - jan-janssen
