{% set name = "cfn-lint" %}
{% set version = "0.44.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6889c171eb2bbbe9e175149d8bada8ae627137748c42b04581e79469dc6b35e7

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33 or py==34]
  entry_points:
    - cfn-lint = cfnlint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - aws-sam-translator >=1.25.0
    - importlib_resources ~=1.4  # [py<37]
    - jsonpatch
    - jsonschema ~=3.0
    - junit-xml ~=1.9
    - networkx ~=2.4  # [py>=35]
    - pathlib2 >=2.3.0  # [py<=34]
    - pyrsistent <=0.16.0  # [py<35]
    - python
    - pyyaml
    - six ~=1.11

test:
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - pip check
    - cfn-lint --help
  requires:
    - pip

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
  license: MIT
  license_file: LICENSE
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint


extra:
  recipe-maintainers:
    - mariusvniekerk
    - hajapy
