{% set name = "cfn-lint" %}
{% set version = "1.22.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8b4f55e283143e99d8d331627637226c291cecfb936606f7aab2d940e71e566d

build:
  number: 0
  noarch: python
  entry_points:
    - cfn-lint = cfnlint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools >=65.5.1
  run:
    - typing_extensions
    - python >=3.8,<4.0
    - pyyaml >5.4
    - aws-sam-translator >=1.94.0
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.0.0
    - regex
    - typing-extensions
    - pydot
    - junit-xml >=1.9,<2.dev0
    - jschema-to-python >=1.2.3,<1.3.dev0
    - sarif-om >=1.0.4,<1.1.dev0

test:
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
  license: MIT
  license_file: LICENSE
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint


extra:
  recipe-maintainers:
    - mariusvniekerk
    - hajapy
    - jan-janssen
